### ISSUE TITLE
Extend the demonstration with other backends and other build steps?

### ISSUE THREAD

**Issue by abelcheung** [layday/flit-scm-demo#1]
Thanks for posting this idea of wrapping up the build backend, it saved my day.

And I just come across the idea of using it to insert arbitrary build steps, not just getting version info via `setuptools-scm`. To my delight, it is quite usable for any backend that doesn't support user defined build steps (like generating DB file or intermediate python source for sdist).

As a bonus, [PDM](https://pdm.fming.dev/) actually works without hampering workflow — unlike the case of `flit`, `pdm build` actually works fine! So probably people utilizing some other backends could use the same approach as stopgap measure.

There is no need for thorough documentation, just a few comments in the backend wrapper and `pyproject.toml` would be enough to document the extensibility, no?

**Comment by layday** [comment]
Yes, you can extend any PEP 517 backend by wrapping its API in a local package/module. I don't know if this is a pattern I would want to encourage though. I fear it might be prone to abuse, much like setuptools commands, which people have repurposed to do all sorts of crazy stuff. You can also only run something either _before_ or _after_ a build this way; often, what you might actually want, is to receive some data from the backend and alter its output in some way, but that's not possible.

**Comment by abelcheung** [comment]
> ...it might be prone to abuse, much like setuptools commands, which people have repurposed...

Yeah, it is quite possible, but I'm a bit more optimistic though. The most serious offenders wouldn't even bother checking out what PEP 517/621 is, and continue working in their own way. People who are willing to investigate the backends are at least more inclined to keep things in check.

> ...can also only run something either _before_ or _after_ a build this way...

Hmph, that's indeed a restriction difficult to circumvent. Generally there are no other chances to hook into building process, post-build in particular. If that kind of versatility is needed, maybe... _long live setuptools!_

**Comment by abelcheung** [comment]
Somebody is creating a [full fledged solution](https://gitlab.com/WillDaSilva/flit_scm) now, @layday you may want to redirect others to there if necessary. Personally I have jumped ship to other backends so this restriction won't bother anymore.

**Comment by layday** [comment]
My suggestion would be to use Poetry or hatch for SCM integration or even setuptools which now supports PEP 621 configuration.
